catalog:
  - catalog/**
  # Change to the CI + CD workflow should trigger complete workflow.
  - .github/workflows/ci_cd.yml
api:
  - api/**
  # Change to the CI + CD workflow should trigger complete workflow.
  - .github/workflows/ci_cd.yml
ingestion_server:
  - ingestion_server/**
  # Change to the CI + CD workflow should trigger complete workflow.
  - .github/workflows/ci_cd.yml
frontend:
  - frontend/**
  - package.json
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - .npmrc
  - .pnpmfile.cjs
  # Change to the CI + CD workflow should trigger complete workflow.
  - .github/workflows/ci_cd.yml
documentation:
  - documentation/**
  - frontend/.storybook/**
  - frontend/**.stories.mdx
  - frontend/nuxt.config.ts
  - frontend/tailwind.config.js
lint:
  - prettier.config.js
  - .prettierignore
  - .eslintrc.js
  - .eslintignore
  - .pre-commit-config.yaml
